-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20

	NDefines.NGame.END_DATE = "1900.1.10"
	NDefines.NCountry.HRE_MAX_RANK = 2
	NDefines.NCountry.FREE_IDEA_GROUP_COST = 4
	NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_STABILITY_COST = 0
	NDefines.NDiplomacy.IMPERIAL_AUTHORITY_FROM_PRINCES = 0.050
	NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STABILITY = 0.35
	NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STATE_WITH_PROSPERITY = 0.05
	NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_TRIBUTARY_DEV = 0.15
	NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_COST = 50
	NDefines.NAI.DEVELOPMENT_CAP_BASE = 100
	NDefines.NAI.AI_TOTAL_DEV_CULTURE_MULTIPLIER = 20
	NDefines.NAI.DEVELOPMENT_CAP_MULT = 1.5
	NDefines.NAI.EDICT_VALUE_THRESHOLD = 5
	NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_DEFICIT = 3
	NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_LOW_INCOME = 1
	NDefines.NAI.STATE_MAINTENANCE_BUDGET_FRACTION = 0.8
	NDefines.NAIEconomy.STATE_MAINTENANCE_FRACTION = 0.8
	NDefines.NAI.AGGRESSIVENESS = 850.0
	NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 800.0
	NDefines.NAI.FORT_CAPITAL_DESIRE = 100
	NDefines.NAI.ARMY_BUDGET_FRACTION = 4.0
	NDefines.NAIEconomy.BUDGETING_ADJUSTMENT_STEP = 0.11
	NDefines.NAIEconomy.MILITARY_FOCUS_DEFAULT = 2.0
	NDefines.NAIEconomy.MILITARY_FOCUS_LOWER_BOUND = 2.0
	NDefines.NAIEconomy.MILITARY_FOCUS_UPPER_BOUND = 3.5
	NDefines.NAI.NOMINAL_ARMY_SIZE_MULTIPLIER = 1.25
	NDefines.NAIEconomy.ARMY_FRACTION_PEACEFUL = 2.1
	NDefines.NAIEconomy.ARMY_FRACTION_MILITARIST = 2.5
	NDefines.NAIEconomy.ARMY_FRACTION_MILITARIZE = 2.2
	NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS = 24
	NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS_PEACETIME = 48
	NDefines.NAI.MAX_BUILDING_COST_INCOME_MONTHS = 30
	NDefines.NAI.MAX_SAVINGS = 40
	NDefines.NAI.DESIRED_DEFICIT = 0.2
	NDefines.NAI.DESIRED_SURPLUS = 0.3
	NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS = 3
	NDefines.NAI.ONLY_INFANTRY_MERCS = 0
	NDefines.NAI.REPAY_LOAN_BASE_AI_DESIRE = 5
	NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY = 1000
	NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY_WARTIME = 0
	NDefines.NAI.DEFENDER_OF_FAITH_BASE_AI_DESIRE = 1
	NDefines.NDiplomacy.AE_DIFFERENT_RELIGION = -0.2
	NDefines.NDiplomacy.AE_SAME_RELIGION_GROUP = 0.1
	NDefines.NDiplomacy.AE_INFIDEL_CONQUEST = 0.5
	-- We keep track of them manually so countries like Lithuania and Francia
	-- can spawn them via Mission Tree, but to avoid Protestant and Reformed
	-- can't set more than 3
	NDefines.NReligion.MAX_CHRISTIAN_RELIGIOUS_CENTERS = 20
	